import React, { createContext, useContext, useEffect, useState } from 'react';

export const translations = {
    fr: {
        // Navigation & Layout
        dashboard: "Tableau de Bord",
        structure: "Structure Administrative",
        directions: "Directions",
        departements: "Départements",
        divisions: "Divisions",
        services: "Services",
        employes: "Employés",
        parc_materiel: "Parc Matériel",
        materiels: "Inventaire Matériels",
        categories: "Catégories",
        affectations: "Affectations",
        journal_audit: "Journal d'Audit",
        administration: "Administration",
        roles: "Gestion des Rôles",
        utilisateurs: "Comptes Utilisateurs",
        actions: "Actions",
        search: "Rechercher",
        search_placeholder: "Recherche rapide...",
        filters: "Filtres",
        close: "Fermer",
        save: "Enregistrer",
        cancel: "Annuler",
        confirm: "Confirmer",
        edit: "Modifier",
        delete: "Supprimer",
        add: "Ajouter",
        create: "Créer",
        status: "Statut",
        total: "Total",
        all: "Tous",
        none: "Aucun",
        yes: "Oui",
        no: "Non",
        details: "Détails",
        active: "Actif",
        inactive: "Inactif",
        online: "En ligne",
        offline: "Hors ligne",
        export_csv: "Exporter CSV",
        light_mode: "Mode Clair",
        dark_mode: "Mode Sombre",
        my_profile: "Mon Profil",
        logout: "Déconnexion",
        back: "Retour",
        print: "Imprimer",
        loading: "Chargement...",
        success: "Succès",
        error: "Erreur",
        warning: "Attention",
        info: "Information",
        validation_error: "Erreur de validation",
        unspecified: "Non spécifié",
        unattached: "Non rattaché",

        // Pagination
        pagination_showing: "Affichage de {from} à {to} sur {total} résultat(s)",
        pagination_lines: "Lignes :",
        pagination_prev: "Page précédente",
        pagination_next: "Page suivante",
        pagination_no_data: "Aucun élément trouvé",

        // Dashboard
        dashboard_title: "Tableau de bord exécutif",
        dashboard_welcome: "Bonjour, {name} 👋",
        dashboard_welcome_sub: "Bienvenue sur la plateforme de gestion centralisée du parc informatique.",
        dashboard_availability: "Disponibilité",
        dashboard_total_hardware: "Matériels au total",
        dashboard_assigned: "Actuellement affectés",
        dashboard_available_stock: "Disponibles en stock",
        dashboard_alert_title: "Alerte Suivi : {count} matériel(s) affecté(s) depuis plus de {months} mois",
        dashboard_alert_sub: "Équipements en détention prolongée. Veuillez effectuer un contrôle physique ou renouveler la prise en charge.",
        dashboard_alert_threshold: "Seuil :",
        dashboard_alert_see_all: "Consulter la liste complète →",
        dashboard_alert_empty: "Aucun matériel en détention prolongée au-delà de {months} mois.",
        dashboard_recent_affectations: "Dernières Affectations Enregistrées",
        dashboard_hardware_status: "Statut du Parc Matériel",
        dashboard_quick_actions: "Accès Rapides",
        dashboard_assigned_on: "Affecté le {date}",
        dashboard_financials: "Engagements Budgétaires & Facturation",
        dashboard_budget_total: "Budget Engagé (HT)",
        dashboard_invoiced_total: "Total Facturé (TTC)",
        dashboard_delivery_fulfillment: "Taux de Livraison Global",
        dashboard_category_distribution: "Répartition du Parc par Catégorie",
        dashboard_recent_activity: "Journal d'Activité Récente & Sécurité",
        dashboard_available_ready: "Équipements Disponibles en Stock",

        // Materiels
        materiels_title: "Gestion du Parc Matériel",
        materiels_add_new: "Ajouter un nouveau matériel",
        materiels_edit: "Modifier le matériel : {name}",
        materiels_nom: "Désignation",
        materiels_marque: "Marque",
        materiels_modele: "Modèle",
        materiels_sn: "N° de Série (Unique)",
        materiels_inv: "N° d'Inventaire (Unique)",
        materiels_categorie: "Catégorie",
        materiels_caracteristiques: "Caractéristiques techniques",
        materiels_disponible: "Disponible en stock",
        materiels_affecte: "En service / Affecté",
        materiels_filter_category: "Filtrer par Catégorie",
        materiels_filter_status: "Filtrer par Statut",
        materiels_save_btn: "Enregistrer le matériel",
        materiels_delete_confirm: "Supprimer ce matériel ?",

        // Affectations
        affectations_title: "Gestion des Affectations",
        affectations_new: "Nouvelle Affectation",
        affectations_all: "Toutes les affectations",
        affectations_active: "En cours",
        affectations_closed: "Clôturées / Restituées",
        affectations_prolonged: "Prolongées (+ de {months} mois)",
        affectations_select_equipment: "Sélectionner le Matériel Disponible *",
        affectations_select_beneficiary: "Sélectionner l'Employé Bénéficiaire *",
        affectations_date_affectation: "Date d'affectation *",
        affectations_date_retour: "Date de restitution prévue",
        affectations_observation: "Observations / Motif d'affectation",
        affectations_restitution_date: "Date de restitution effective *",
        affectations_restitution_obs: "Observations de retour (état du matériel, accessoires...)",
        affectations_close_modal_title: "Clôturer l'affectation & Restituer le matériel",
        affectations_close_btn: "Valider la restitution",
        affectations_print_sheet: "Fiche de Décharge A4",
        affectations_prolonged_badge: "⚠️ Affecté depuis {duration} mois (Seuil: {threshold} mois)",

        // Employes
        employes_title: "Gestion des Employés & Collaborateurs",
        employes_add_new: "Ajouter un nouvel employé",
        employes_edit: "Modifier l'employé : {name}",
        employes_matricule: "Matricule (Unique)",
        employes_nom: "Nom de famille",
        employes_prenom: "Prénom",
        employes_fonction: "Fonction / Poste",
        employes_service: "Service de rattachement",
        employes_filter_service: "Filtrer par Service",
        employes_delete_confirm: "Supprimer cet employé ?",

        // Structure (Directions, Départements, Divisions, Services)
        structure_title: "Structure Administrative",
        directions_title: "Gestion des Directions",
        directions_add: "Ajouter une nouvelle direction",
        directions_name: "Nom de la direction (Unique)",
        directions_edit: "Modifier la direction : {name}",
        directions_attached_deps: "Départements Rattachés",

        departements_title: "Gestion des Départements",
        departements_add: "Ajouter un nouveau département",
        departements_name: "Nom du département (Unique)",
        departements_edit: "Modifier le département : {name}",
        departements_attached_dir: "Direction de rattachement",
        departements_attached_divs: "Divisions Rattachées",

        divisions_title: "Gestion des Divisions",
        divisions_add: "Ajouter une nouvelle division",
        divisions_name: "Nom de la division (Unique)",
        divisions_edit: "Modifier la division : {name}",
        divisions_attached_dep: "Département de rattachement",
        divisions_attached_services: "Services Rattachés",

        services_title: "Gestion des Services",
        services_add: "Ajouter un nouveau service",
        services_name: "Nom du service (Unique)",
        services_edit: "Modifier le service : {name}",
        services_attached_div: "Division de rattachement",
        services_attached_employes: "Employés Rattachés",
        services_hierarchy: "Hiérarchie Structurelle (Direction ➜ Dép. ➜ Division)",

        // Categories
        categories_title: "Inventaire des Catégories",
        categories_add: "Ajouter une nouvelle catégorie",
        categories_name: "Nom de la catégorie (Unique)",
        categories_edit: "Modifier la catégorie : {name}",
        categories_attached_hardware: "Matériels Associés",

        // Roles & Permissions
        roles_title: "Gestion des Rôles & Habilitations",
        roles_add: "Créer un nouveau rôle",
        roles_name: "Nom du rôle (Unique)",
        roles_desc: "Description de la responsabilité",
        roles_edit: "Modifier le rôle : {name}",
        roles_catalog: "Catalogue des Permissions Prédéfinies",
        roles_active_perms: "{count} / {total} actives",
        roles_module: "Module : {name} (Big Permission)",

        // Users
        users_title: "Comptes Utilisateurs & Accès",
        users_add: "Ajouter un nouvel utilisateur",
        users_name: "Nom complet",
        users_email: "Adresse Email (Unique)",
        users_password: "Mot de passe",
        users_role: "Rôle Système",
        users_attached_emp: "Employé Associé (Optionnel)",
        users_reset_password: "Réinitialiser le mot de passe",
        users_new_password: "Nouveau mot de passe",
        users_status_active: "Compte Actif",
        users_status_inactive: "Compte Bloqué / Inactif",

        // Audit Logs
        audit_title: "Journal d'Audit & Sécurité",
        audit_sub: "Registre infalsifiable traçant l'ensemble des opérations et mouvements du parc.",
        audit_event: "Événement / Action",
        audit_module: "Module",
        audit_user: "Auteur / Utilisateur",
        audit_ip: "Adresse IP",
        audit_date: "Date & Horodatage",
        audit_details: "Détails de l'opération",

        // Fiche de Décharge (Print A4)
        print_title: "Fiche de Décharge & Prise en Charge Matériel",
        print_doc_ready: "Document officiel prêt pour l'impression A4",
        print_button: "Imprimer la Fiche",
        print_heading: "FICHE DE MISE À DISPOSITION & DÉCHARGE MATÉRIEL",
        print_discharge_title: "FICHE DE DÉCHARGE DU MATÉRIEL INFORMATIQUE",
        print_ref: "Réf. Affectation",
        print_date: "Date d'édition",
        print_section_beneficiary: "INFORMATIONS DU BÉNÉFICIAIRE",
        print_section_materiel: "DÉSIGNATION DU MATÉRIEL AFFECTÉ",
        print_section_commitments: "ENGAGEMENTS DU BÉNÉFICIAIRE & CONDITIONS D'UTILISATION",
        print_term_1: "Le bénéficiaire s'engage à utiliser le matériel exclusivement dans le cadre professionnel et conformément à la charte informatique de l'entreprise.",
        print_term_2: "Il est tenu d'assurer la garde, la préservation et la sécurité physique et logique des équipements confiés.",
        print_term_3: "Toute anomalie, panne, détérioration, perte ou vol doit être immédiatement signalée à la Direction des Systèmes d'Information (DSI).",
        print_term_4: "Le matériel demeure la propriété exclusive de l'organisme et doit être restitué sans délai à la cessation des fonctions ou sur demande de la DSI.",
        print_section_signatures: "ÉMARGEMENT & VALIDATION",
        print_sig_beneficiary: "Le Bénéficiaire",
        print_sig_beneficiary_sub: "Signature précédée de la mention « Lu et approuvé »",
        print_sig_supervisor: "Le Supérieur Hiérarchique",
        print_sig_supervisor_sub: "Nom, Visa & Cachet",
        print_sig_dsitd: "La Direction des Systèmes d'Information",
        print_sig_dsitd_sub: "Visa du Responsable Parc & Validation",
        materiels_name: "Désignation",
        materiels_category: "Catégorie",
        materiels_brand: "Marque",
        materiels_model: "Modèle",
        materiels_serial: "N° Série",
        materiels_inventory: "N° Inventaire",

        // Alerts & Validation
        alert_success_operation: "Opération réalisée avec succès.",
        alert_error_operation: "Une erreur est survenue lors du traitement.",
        alert_duplicate_detected: "Doublon détecté sur un attribut unique.",

        // Welcome Landing Page
        system_title: "PARC INFORMATIQUE",
        system_subtitle: "GESTION EXECUTIVE",
        hero_badge: "Système Opérationnel & Conforme v2.0",
        hero_title_1: "Gestion Executive du",
        hero_title_2: "Parc Informatique",
        hero_desc: "Traçabilité intégrale des équipements, gestion des affectations par collaborateur, alertes de renouvellement et journal d'audit sécurisé.",
        go_to_dashboard: "Accéder au Tableau de Bord →",
        login_access: "Connexion à l'Espace Sécurisé →",
        workspace_access: "Espace de Travail →",
        live_preview_title: "Aperçu Executive Live",
        live_preview_desc: "Dernières données du parc en temps réel",
        stat_total_title: "Inventaire Matériel",
        stat_total_sub: "Total Équipements",
        stat_total_desc: "Traçabilité par S/N et Code Inventaire",
        stat_stock_title: "Stock & Sécurité",
        stat_stock_sub: "Stock Disponible",
        stat_stock_desc: "Audit continu et contrôle des rôles",
        login_btn: "Se connecter",
        register_btn: "S'inscrire",
        create_account: "Créer un compte",
        no_account: "Vous n'avez pas encore de compte ?",
        already_account: "Vous avez déjà un compte ?",
        remember_me: "Se souvenir de moi",
        forgot_password: "Mot de passe oublié ?",
        login_title: "Connexion à votre espace",
        login_subtitle: "Accédez à la plateforme de gestion du parc informatique",
        register_title: "Créer un nouveau compte",
        register_subtitle: "Rejoignez la plateforme de gestion du parc informatique",
        name_label: "Nom complet",
        email_label: "Adresse Email",
        password_label: "Mot de passe",
        confirm_password_label: "Confirmer le mot de passe",
        // Achats & Fournisseurs & Stocks
        achats_stocks: "Achats & Stocks",
        fournisseurs: "Fournisseurs",
        fournisseurs_title: "Annuaire des Fournisseurs",
        fournisseurs_subtitle: "Gestion des prestataires et partenaires matériels",
        fournisseurs_add: "Nouveau Fournisseur",
        fournisseurs_edit: "Modifier le Fournisseur",
        fournisseur_name: "Nom du Fournisseur",
        fournisseur_address: "Adresse",
        fournisseur_phone: "Téléphone",
        fournisseur_contact: "Personne de Contact",
        fournisseur_achats_count: "Marchés / Achats associés",

        achats: "Achats & Marchés",
        achats_title: "Gestion des Achats & Marchés",
        achats_subtitle: "Suivi des commandes, marchés publics et bons de commande",
        achats_add: "Nouvel Achat / Marché",
        achats_edit: "Modifier l'Achat",
        achat_numero: "N° Achat / Marché",
        achat_objet: "Objet de la commande",
        achat_type: "Type d'achat",
        achat_date: "Date de passation",
        achat_statut: "État d'avancement",
        achat_total_ht: "Montant Total HT",
        achat_total_ttc: "Total Facturé TTC",
        achat_lignes_count: "Lignes commandées",
        achat_qte_totale: "Quantité Totale",
        achat_qte_recue: "Quantité Réceptionnée",
        achat_details: "Détails du Marché & Bordereau",
        filter_achat: "Filtrer par Achat / Marché",
        all_achats: "Tous les Achats / Marchés",

        bordereau_title: "Bordereau des Prix & Lignes Matériels",
        bordereau_add_line: "Ajouter une ligne au bordereau",
        bordereau_designation: "Désignation Matériel",
        bordereau_specs: "Caractéristiques techniques",
        bordereau_qte: "Qté Commandée",
        bordereau_garantie: "Garantie (mois)",
        bordereau_pu_ht: "P.U. HT (DH)",
        bordereau_total_ht: "Total Ligne HT",
        bordereau_delivered: "Livré",
        bordereau_remaining: "Reste à livrer",

        factures: "Factures",
        factures_title: "Suivi des Factures Fournisseurs",
        factures_subtitle: "Enregistrement comptable et liquidation des paiements",
        factures_add: "Enregistrer une Facture",
        facture_numero: "N° Facture",
        facture_date: "Date Facture",
        facture_montant_ht: "Montant HT",
        facture_tva: "Taux TVA (%)",
        facture_montant_ttc: "Montant TTC",

        livraisons: "Livraisons & Stocks",
        livraisons_title: "Bons de Livraison & Réceptions Stock",
        livraisons_subtitle: "Entrée en stock et immobilisation d'équipements",
        livraisons_add: "Nouvelle Réception BL",
        livraison_ref: "Réf. Bon de Livraison (BL)",
        livraison_date: "Date Réception",
        livraison_qte: "Quantité Réceptionnée",
        livraison_auto_generate: "Générer automatiquement les fiches d'inventaire matériels (Immobilisation)",
        livraison_prefix: "Préfixe N° Inventaire",

        marques_modeles: "Marques & Modèles",
        marques_title: "Référentiel Marques & Modèles",
        marques_subtitle: "Catalogue des constructeurs et gammes d'équipements",
        marques_add: "Nouvelle Marque",
        marques_edit: "Modifier la Marque",
        modeles_add: "Nouveau Modèle",
        modeles_edit: "Modifier le Modèle",
        marque_name: "Nom de la Marque",
        modele_name: "Nom du Modèle",
        modeles_count: "Nombre de modèles",

        bulk_import: "Importation en Masse",
        bulk_import_btn: "📥 Import Excel / CSV",
        bulk_import_title: "Importer des Matériels en Masse",
        bulk_import_subtitle: "Téléversez un fichier Excel ou CSV pour créer plusieurs matériels en un seul clic.",
        bulk_import_download_template: "Télécharger le modèle Excel / CSV",
        bulk_import_file_label: "Fichier Excel / CSV (.csv, .xlsx, .xls)",
        bulk_import_submit: "Lancer l'importation",
        bulk_import_results: "Résultats de l'importation",
        materiel_achat: "Achat / Marché d'origine",
        materiel_achat_placeholder: "-- Sélectionner un Achat / Marché (Optionnel) --",

        feature_structure_title: "Structure Organisationnelle",
        feature_structure_desc: "Découpage hiérarchique complet par Directions, Départements, Divisions et Services avec rattachement direct des collaborateurs.",
        feature_parc_title: "Parc & Affectations",
        feature_parc_desc: "Attributions d'ordinateurs, écrans et périphériques avec gestion de restitutions, clôtures et fiches de prise en charge A4.",
        feature_security_title: "Sécurité & Journal d'Audit",
        feature_security_desc: "Registre infalsifiable traçant l'ensemble des créations, modifications et clôtures d'affectations avec horodatage strict.",
        footer_internal: "— Système de Gestion Interne",
        footer_rights: "Tous droits réservés."
    },
    en: {
        // Navigation & Layout
        dashboard: "Dashboard",
        structure: "Administrative Structure",
        directions: "Directions",
        departements: "Departments",
        divisions: "Divisions",
        services: "Services",
        employes: "Employees",
        parc_materiel: "Hardware Fleet",
        materiels: "Hardware Inventory",
        categories: "Categories",
        affectations: "Assignments",
        journal_audit: "Audit Logs",
        administration: "Administration",
        roles: "Role Management",
        utilisateurs: "User Accounts",
        actions: "Actions",
        search: "Search",
        search_placeholder: "Quick search...",
        filters: "Filters",
        close: "Close",
        save: "Save",
        cancel: "Cancel",
        confirm: "Confirm",
        edit: "Edit",
        delete: "Delete",
        add: "Add",
        create: "Create",
        status: "Status",
        total: "Total",
        all: "All",
        none: "None",
        yes: "Yes",
        no: "No",
        details: "Details",
        active: "Active",
        inactive: "Inactive",
        online: "Online",
        offline: "Offline",
        export_csv: "Export CSV",
        light_mode: "Light Mode",
        dark_mode: "Dark Mode",
        my_profile: "My Profile",
        logout: "Logout",
        back: "Back",
        print: "Print",
        loading: "Loading...",
        success: "Success",
        error: "Error",
        warning: "Warning",
        info: "Information",
        validation_error: "Validation Error",
        unspecified: "Unspecified",
        unattached: "Unattached",

        // Pagination
        pagination_showing: "Showing {from} to {to} of {total} result(s)",
        pagination_lines: "Rows:",
        pagination_prev: "Previous Page",
        pagination_next: "Next Page",
        pagination_no_data: "No records found",

        // Dashboard
        dashboard_title: "Executive Dashboard",
        dashboard_welcome: "Hello, {name} 👋",
        dashboard_welcome_sub: "Welcome to the centralized IT fleet management platform.",
        dashboard_availability: "Availability",
        dashboard_total_hardware: "Total Hardware",
        dashboard_assigned: "Currently Assigned",
        dashboard_available_stock: "In Stock",
        dashboard_alert_title: "Monitoring Alert: {count} equipment item(s) assigned for over {months} months",
        dashboard_alert_sub: "Equipment in prolonged retention. Please conduct a physical check or renew the agreement.",
        dashboard_alert_threshold: "Threshold:",
        dashboard_alert_see_all: "View Full List →",
        dashboard_alert_empty: "No hardware in prolonged retention beyond {months} months.",
        dashboard_recent_affectations: "Recent Hardware Assignments",
        dashboard_hardware_status: "Hardware Fleet Status",
        dashboard_quick_actions: "Quick Actions",
        dashboard_assigned_on: "Assigned on {date}",
        dashboard_financials: "Budget Engagements & Invoicing",
        dashboard_budget_total: "Total Budget Engaged (HT)",
        dashboard_invoiced_total: "Total Invoiced (TTC)",
        dashboard_delivery_fulfillment: "Overall Delivery Rate",
        dashboard_category_distribution: "Fleet Distribution by Category",
        dashboard_recent_activity: "Recent Activity & Security Feed",
        dashboard_available_ready: "Available Hardware in Stock",

        // Materiels
        materiels_title: "Hardware Fleet Management",
        materiels_add_new: "Add New Equipment",
        materiels_edit: "Edit Equipment: {name}",
        materiels_nom: "Designation",
        materiels_marque: "Brand",
        materiels_modele: "Model",
        materiels_sn: "Serial Number (Unique)",
        materiels_inv: "Inventory Number (Unique)",
        materiels_categorie: "Category",
        materiels_caracteristiques: "Technical Specifications",
        materiels_disponible: "In Stock / Available",
        materiels_affecte: "In Service / Assigned",
        materiels_filter_category: "Filter by Category",
        materiels_filter_status: "Filter by Status",
        materiels_save_btn: "Save Equipment",
        materiels_delete_confirm: "Delete this equipment item?",

        // Affectations
        affectations_title: "Assignment Management",
        affectations_new: "New Assignment",
        affectations_all: "All Assignments",
        affectations_active: "Active",
        affectations_closed: "Closed / Returned",
        affectations_prolonged: "Prolonged (+ {months} months)",
        affectations_select_equipment: "Select Available Equipment *",
        affectations_select_beneficiary: "Select Beneficiary Employee *",
        affectations_date_affectation: "Assignment Date *",
        affectations_date_retour: "Expected Return Date",
        affectations_observation: "Observations / Purpose of Assignment",
        affectations_restitution_date: "Actual Return Date *",
        affectations_restitution_obs: "Return notes (hardware condition, accessories...)",
        affectations_close_modal_title: "Close Assignment & Return Equipment",
        affectations_close_btn: "Confirm Return",
        affectations_print_sheet: "A4 Handover Slip",
        affectations_prolonged_badge: "⚠️ Assigned for {duration} months (Threshold: {threshold} months)",

        // Employes
        employes_title: "Employee & Staff Management",
        employes_add_new: "Add New Employee",
        employes_edit: "Edit Employee: {name}",
        employes_matricule: "Employee ID (Unique)",
        employes_nom: "Last Name",
        employes_prenom: "First Name",
        employes_fonction: "Job Title / Position",
        employes_service: "Attached Service",
        employes_filter_service: "Filter by Service",
        employes_delete_confirm: "Delete this employee?",

        // Structure
        structure_title: "Administrative Structure",
        directions_title: "Directorate Management",
        directions_add: "Add New Directorate",
        directions_name: "Directorate Name (Unique)",
        directions_edit: "Edit Directorate: {name}",
        directions_attached_deps: "Attached Departments",

        departements_title: "Department Management",
        departements_add: "Add New Department",
        departements_name: "Department Name (Unique)",
        departements_edit: "Edit Department: {name}",
        departements_attached_dir: "Parent Directorate",
        departements_attached_divs: "Attached Divisions",

        divisions_title: "Division Management",
        divisions_add: "Add New Division",
        divisions_name: "Division Name (Unique)",
        divisions_edit: "Edit Division: {name}",
        divisions_attached_dep: "Parent Department",
        divisions_attached_services: "Attached Services",

        services_title: "Service Management",
        services_add: "Add New Service",
        services_name: "Service Name (Unique)",
        services_edit: "Edit Service: {name}",
        services_attached_div: "Parent Division",
        services_attached_employes: "Attached Employees",
        services_hierarchy: "Structural Hierarchy (Directorate ➜ Dept ➜ Division)",

        // Categories
        categories_title: "Category Inventory",
        categories_add: "Add New Category",
        categories_name: "Category Name (Unique)",
        categories_edit: "Edit Category: {name}",
        categories_attached_hardware: "Associated Equipment",

        // Roles & Permissions
        roles_title: "Role & Permission Management",
        roles_add: "Create New Role",
        roles_name: "Role Name (Unique)",
        roles_desc: "Responsibility Description",
        roles_edit: "Edit Role: {name}",
        roles_catalog: "Predefined Permission Catalog",
        roles_active_perms: "{count} / {total} active",
        roles_module: "Module: {name} (Big Permission)",

        // Users
        users_title: "User Accounts & Access",
        users_add: "Add New User",
        users_name: "Full Name",
        users_email: "Email Address (Unique)",
        users_password: "Password",
        users_role: "System Role",
        users_attached_emp: "Attached Employee (Optional)",
        users_reset_password: "Reset Password",
        users_new_password: "New Password",
        users_status_active: "Active Account",
        users_status_inactive: "Blocked / Inactive Account",

        // Audit Logs
        audit_title: "Audit Log & Security",
        audit_sub: "Tamper-proof record tracking all operations and hardware fleet movements.",
        audit_event: "Event / Action",
        audit_module: "Module",
        audit_user: "Author / User",
        audit_ip: "IP Address",
        audit_date: "Date & Timestamp",
        audit_details: "Operation Details",

        // Print Discharge (A4 Sheet)
        print_title: "Equipment Handover & Custody Form",
        print_doc_ready: "Official document ready for A4 printing",
        print_button: "Print Handover Sheet",
        print_heading: "HARDWARE HANDOVER & CUSTODY SHEET",
        print_discharge_title: "IT HARDWARE HANDOVER & DISCHARGE SLIP",
        print_ref: "Assignment Ref",
        print_date: "Issue Date",
        print_section_beneficiary: "BENEFICIARY INFORMATION",
        print_section_materiel: "ASSIGNED HARDWARE SPECIFICATIONS",
        print_section_commitments: "BENEFICIARY COMMITMENTS & TERMS OF USE",
        print_term_1: "The beneficiary agrees to use the equipment exclusively for professional purposes in accordance with the organization's IT policy.",
        print_term_2: "The beneficiary is responsible for safeguarding and ensuring the physical and logical security of the assigned equipment.",
        print_term_3: "Any malfunction, damage, loss, or theft must be reported immediately to the IT Department (DSITD).",
        print_term_4: "The equipment remains the exclusive property of the organization and must be returned upon termination of duties or upon request.",
        print_section_signatures: "SIGNATURES & VALIDATION",
        print_sig_beneficiary: "The Beneficiary",
        print_sig_beneficiary_sub: "Signature preceded by 'Read and approved'",
        print_sig_supervisor: "Line Manager",
        print_sig_supervisor_sub: "Name, Visa & Stamp",
        print_sig_dsitd: "Information Systems Directorate",
        print_sig_dsitd_sub: "Fleet Manager Visa & Stamp",
        materiels_name: "Designation",
        materiels_category: "Category",
        materiels_brand: "Brand",
        materiels_model: "Model",
        materiels_serial: "Serial Number",
        materiels_inventory: "Inventory Code",

        // Alerts & Validation
        alert_success_operation: "Operation completed successfully.",
        alert_error_operation: "An error occurred while processing.",
        alert_duplicate_detected: "Duplicate detected on a unique attribute.",

        // Welcome Landing Page
        system_title: "IT FLEET MANAGEMENT",
        system_subtitle: "EXECUTIVE MANAGEMENT",
        hero_badge: "Operational & Compliant System v2.0",
        hero_title_1: "Executive Management of",
        hero_title_2: "IT Hardware Fleet",
        hero_desc: "Full equipment traceability, employee assignment tracking, renewal alerts, and secure audit logs.",
        go_to_dashboard: "Access Dashboard →",
        login_access: "Secure Login →",
        workspace_access: "Workspace →",
        live_preview_title: "Live Executive Preview",
        live_preview_desc: "Real-time hardware fleet status",
        stat_total_title: "Hardware Inventory",
        stat_total_sub: "Total Equipment",
        stat_total_desc: "Traceability by S/N and Tag",
        stat_stock_title: "Stock & Security",
        stat_stock_sub: "Available Stock",
        stat_stock_desc: "Continuous audit and role access control",
        login_btn: "Log In",
        register_btn: "Register",
        create_account: "Create an Account",
        no_account: "Don't have an account yet?",
        already_account: "Already have an account?",
        remember_me: "Remember me",
        forgot_password: "Forgot your password?",
        login_title: "Sign in to your account",
        login_subtitle: "Access the IT fleet management platform",
        register_title: "Create a new account",
        register_subtitle: "Join the IT fleet management platform",
        name_label: "Full Name",
        email_label: "Email Address",
        password_label: "Password",
        confirm_password_label: "Confirm Password",
        // Achats & Fournisseurs & Stocks
        achats_stocks: "Purchases & Stocks",
        fournisseurs: "Suppliers",
        fournisseurs_title: "Suppliers Directory",
        fournisseurs_subtitle: "Vendor and provider management",
        fournisseurs_add: "New Supplier",
        fournisseurs_edit: "Edit Supplier",
        fournisseur_name: "Supplier Name",
        fournisseur_address: "Address",
        fournisseur_phone: "Phone",
        fournisseur_contact: "Contact Person",
        fournisseur_achats_count: "Associated Purchases",

        achats: "Purchases & Contracts",
        achats_title: "Purchases & Contracts Management",
        achats_subtitle: "Track purchase orders, contracts and procurement",
        achats_add: "New Purchase Order",
        achats_edit: "Edit Purchase",
        achat_numero: "Purchase / Contract No.",
        achat_objet: "Order Purpose",
        achat_type: "Purchase Type",
        achat_date: "Order Date",
        achat_statut: "Status",
        achat_total_ht: "Total Excl. VAT",
        achat_total_ttc: "Total Invoiced Incl. VAT",
        achat_lignes_count: "Ordered Items",
        achat_qte_totale: "Total Quantity",
        achat_qte_recue: "Delivered Quantity",
        achat_details: "Purchase Details & Items",
        filter_achat: "Filter by Purchase / Contract",
        all_achats: "All Purchases / Contracts",

        bordereau_title: "Bill of Quantities & Hardware Items",
        bordereau_add_line: "Add Item to Order",
        bordereau_designation: "Hardware Designation",
        bordereau_specs: "Technical Specs",
        bordereau_qte: "Ordered Qty",
        bordereau_garantie: "Warranty (Months)",
        bordereau_pu_ht: "Unit Price Excl. VAT (DH)",
        bordereau_total_ht: "Line Total Excl. VAT",
        bordereau_delivered: "Delivered",
        bordereau_remaining: "Remaining to deliver",

        factures: "Invoices",
        factures_title: "Supplier Invoices Tracking",
        factures_subtitle: "Accounting records and payment verification",
        factures_add: "Record Invoice",
        facture_numero: "Invoice No.",
        facture_date: "Invoice Date",
        facture_montant_ht: "Amount Excl. VAT",
        facture_tva: "VAT Rate (%)",
        facture_montant_ttc: "Amount Incl. VAT",

        livraisons: "Deliveries & Stock Receipts",
        livraisons_title: "Delivery Slips & Stock Inflow",
        livraisons_subtitle: "Warehouse reception and asset registration",
        livraisons_add: "New Delivery Slip (BL)",
        livraison_ref: "Delivery Ref. (BL)",
        livraison_date: "Receipt Date",
        livraison_qte: "Received Quantity",
        livraison_auto_generate: "Auto-generate asset inventory items (Immobilization)",
        livraison_prefix: "Inventory No. Prefix",

        marques_modeles: "Brands & Models",
        marques_title: "Brands & Models Catalog",
        marques_subtitle: "Manufacturer and hardware model registry",
        marques_add: "New Brand",
        marques_edit: "Edit Brand",
        modeles_add: "New Model",
        modeles_edit: "Edit Model",
        marque_name: "Brand Name",
        modele_name: "Model Name",
        modeles_count: "Number of models",

        bulk_import: "Bulk Import",
        bulk_import_btn: "📥 Bulk Import Excel/CSV",
        bulk_import_title: "Bulk Import Hardware Assets",
        bulk_import_subtitle: "Upload an Excel or CSV file to import multiple hardware assets at once.",
        bulk_import_download_template: "Download Excel / CSV Template",
        bulk_import_file_label: "Excel / CSV File (.csv, .xlsx, .xls)",
        bulk_import_submit: "Start Bulk Import",
        bulk_import_results: "Import Results",
        materiel_achat: "Origin Purchase Order",
        materiel_achat_placeholder: "-- Select a Purchase Order (Optional) --",

        feature_structure_title: "Organizational Structure",
        feature_structure_desc: "Hierarchical breakdown by Directions, Departments, Divisions, and Services with direct employee linking.",
        feature_parc_title: "Fleet & Assignments",
        feature_parc_desc: "Assignment of computers, monitors, and peripherals with returns, closures, and printable A4 sheets.",
        feature_security_title: "Security & Audit Log",
        feature_security_desc: "Tamper-proof log tracking all creation, modification, and closure of assignments with strict timestamps.",
        footer_internal: "— Internal Management System",
        footer_rights: "All rights reserved."
    },
    ar: {
        // Navigation & Layout
        dashboard: "لوحة التحكم",
        structure: "الهيكل التنظيمي",
        directions: "المديريات",
        departements: "الأقسام",
        divisions: "المصالح",
        services: "الخدمات",
        employes: "الموظفون",
        parc_materiel: "العتاد المعلوماتي",
        materiels: "جرد المعدات",
        categories: "الفئات",
        affectations: "التعيينات",
        journal_audit: "سجل التدقيق",
        administration: "الإدارة والنظام",
        roles: "إدارة الأدوار",
        utilisateurs: "حسابات المستخدمين",
        actions: "خيارات",
        search: "بحث",
        search_placeholder: "بحث سريع...",
        filters: "تصفية",
        close: "إغلاق",
        save: "حفظ",
        cancel: "إلغاء",
        confirm: "تأكيد",
        edit: "تعديل",
        delete: "حذف",
        add: "إضافة",
        create: "إنشاء",
        status: "الحالة",
        total: "المجموع",
        all: "الكل",
        none: "لا شيء",
        yes: "نعم",
        no: "لا",
        details: "التفاصيل",
        active: "نشط",
        inactive: "غير نشط",
        online: "متصل",
        offline: "غير متصل",
        export_csv: "تصدير CSV",
        light_mode: "الوضع النهاري",
        dark_mode: "الوضع الليلي",
        my_profile: "الملف الشخصي",
        logout: "تسجيل الخروج",
        back: "رجوع",
        print: "طباعة",
        loading: "جاري التحميل...",
        success: "تمت العملية بنجاح",
        error: "حدث خطأ",
        warning: "تنبيه",
        info: "معلومات",
        validation_error: "خطأ في التحقق من البيانات",
        unspecified: "غير محدد",
        unattached: "غير مخصص",

        // Pagination
        pagination_showing: "عرض من {from} إلى {to} من أصل {total} نتيجة",
        pagination_lines: "الأسطر:",
        pagination_prev: "الصفحة السابقة",
        pagination_next: "الصفحة التالية",
        pagination_no_data: "لا توجد نتائج",

        // Dashboard
        dashboard_title: "لوحة التحكم التنفيذية",
        dashboard_welcome: "مرحباً، {name} 👋",
        dashboard_welcome_sub: "مرحباً بك في المنصة المركزية لإدارة حظيرة العتاد المعلوماتي.",
        dashboard_availability: "نسبة التوفر",
        dashboard_total_hardware: "إجمالي العتاد",
        dashboard_assigned: "المعين حالياً",
        dashboard_available_stock: "المتوفر بالمخزن",
        dashboard_alert_title: "تنبيه متابعة: {count} عتاد معار لأكثر من {months} أشهر",
        dashboard_alert_sub: "أجهزة في فترة إعارة ممتدة. يرجى إجراء فحص فعلي أو تجديد استمارة التعيين.",
        dashboard_alert_threshold: "المدة المحددة:",
        dashboard_alert_see_all: "عرض القائمة الكاملة ←",
        dashboard_alert_empty: "لا يوجد أي عتاد في إعارة ممتدة تتجاوز {months} أشهر.",
        dashboard_recent_affectations: "أحدث عمليات التعيين المسجلة",
        dashboard_hardware_status: "حالة العتاد المعلوماتي",
        dashboard_quick_actions: "إجراءات واختصارات سريعة",
        dashboard_assigned_on: "تم التعيين بتاريخ {date}",
        dashboard_financials: "الالتزامات المالية والفوترة",
        dashboard_budget_total: "إجمالي الميزانية الملتزم بها (HT)",
        dashboard_invoiced_total: "إجمالي الفواتير مع الضريبة (TTC)",
        dashboard_delivery_fulfillment: "نسبة التوصيل العامة",
        dashboard_category_distribution: "توزيع العتاد حسب الفئات",
        dashboard_recent_activity: "سجل العمليات الأخيرة والأمان",
        dashboard_available_ready: "العتاد المتاح في المخزن وجاهز للتكليف",

        // Materiels
        materiels_title: "إدارة العتاد والأجهزة",
        materiels_add_new: "إضافة عتاد جديد",
        materiels_edit: "تعديل بيانات العتاد: {name}",
        materiels_nom: "اسم العتاد",
        materiels_marque: "العلامة التجارية",
        materiels_modele: "الموديل / الطراز",
        materiels_sn: "الرقم التسلسلي (فريد)",
        materiels_inv: "رقم الجرد (فريد)",
        materiels_categorie: "الفئة",
        materiels_caracteristiques: "المواصفات التقنية",
        materiels_disponible: "متوفر بالمخزن",
        materiels_affecte: "قيد الاستعمال / معار",
        materiels_filter_category: "تصفية حسب الفئة",
        materiels_filter_status: "تصفية حسب الحالة",
        materiels_save_btn: "حفظ بيانات العتاد",
        materiels_delete_confirm: "هل تريد حذف هذا العتاد نهائياً؟",

        // Affectations
        affectations_title: "إدارة التعيينات والإعارة",
        affectations_new: "تعيين جديد",
        affectations_all: "كافة التعيينات",
        affectations_active: "قيد الاستعمال",
        affectations_closed: "مسترجعة / مغلقة",
        affectations_prolonged: "إعارة ممتدة (+ {months} أشهر)",
        affectations_select_equipment: "اختر العتاد المتوفر *",
        affectations_select_beneficiary: "اختر الموظف المستفيد *",
        affectations_date_affectation: "تاريخ التعيين *",
        affectations_date_retour: "تاريخ الاسترجاع المتوقع",
        affectations_observation: "ملاحظات / سبب التعيين",
        affectations_restitution_date: "تاريخ الإرجاع الفعلي *",
        affectations_restitution_obs: "ملاحظات الاستلام (حالة العتاد، الملحقات...)",
        affectations_close_modal_title: "إغلاق التعيين واسترجاع العتاد",
        affectations_close_btn: "تأكيد الاسترجاع",
        affectations_print_sheet: "استمارة التسليم A4",
        affectations_prolonged_badge: "⚠️ معار منذ {duration} أشهر (الحد: {threshold} أشهر)",

        // Employes
        employes_title: "إدارة الموظفين والكوادر",
        employes_add_new: "إضافة موظف جديد",
        employes_edit: "تعديل بيانات الموظف: {name}",
        employes_matricule: "رقم التأجير / الماتريكول (فريد)",
        employes_nom: "النسب / اللقب",
        employes_prenom: "الاسم الشخصي",
        employes_fonction: "المسمى الوظيفي / المهمة",
        employes_service: "المصلحة التابع لها",
        employes_filter_service: "تصفية حسب المصلحة",
        employes_delete_confirm: "هل تريد حذف هذا الموظف؟",

        // Structure
        structure_title: "الهيكل التنظيمي",
        directions_title: "إدارة المديريات",
        directions_add: "إضافة مديرية جديدة",
        directions_name: "اسم المديرية (فريد)",
        directions_edit: "تعديل المديرية: {name}",
        directions_attached_deps: "الأقسام التابعة",

        departements_title: "إدارة الأقسام",
        departements_add: "إضافة قسم جديد",
        departements_name: "اسم القسم (فريد)",
        departements_edit: "تعديل القسم: {name}",
        departements_attached_dir: "المديرية التابعة لها",
        departements_attached_divs: "المصالح التابعة",

        divisions_title: "إدارة المصالح",
        divisions_add: "إضافة مصلحة جديدة",
        divisions_name: "اسم المصلحة (فريد)",
        divisions_edit: "تعديل المصلحة: {name}",
        divisions_attached_dep: "القسم التابع له",
        divisions_attached_services: "الخدمات التابعة",

        services_title: "إدارة الخدمات",
        services_add: "إضافة خدمة جديدة",
        services_name: "اسم الخدمة (فريد)",
        services_edit: "تعديل الخدمة: {name}",
        services_attached_div: "المصلحة التابعة لها",
        services_attached_employes: "الموظفون التابعون",
        services_hierarchy: "التسلسل الهيكلي (المديرية ➜ القسم ➜ المصلحة)",

        // Categories
        categories_title: "جرد الفئات",
        categories_add: "إضافة فئة جديدة",
        categories_name: "اسم الفئة (فريد)",
        categories_edit: "تعديل الفئة: {name}",
        categories_attached_hardware: "الأجهزة المرتبطة",

        // Roles & Permissions
        roles_title: "إدارة الأدوار والصلاحيات",
        roles_add: "إنشاء دور جديد",
        roles_name: "اسم الدور (فريد)",
        roles_desc: "وصف الصلاحية والمسؤوليات",
        roles_edit: "تعديل الدور: {name}",
        roles_catalog: "دليل الصلاحيات المتاحة",
        roles_active_perms: "{count} / {total} نشطة",
        roles_module: "الوحدة: {name} (صلاحية رئيسية)",

        // Users
        users_title: "حسابات المستخدمين والدخول",
        users_add: "إضافة مستخدم جديد",
        users_name: "الاسم الكامل",
        users_email: "البريد الإلكتروني (فريد)",
        users_password: "كلمة المرور",
        users_role: "الدور في النظام",
        users_attached_emp: "الموظف المرتبط (اختياري)",
        users_reset_password: "إعادة ضبط كلمة المرور",
        users_new_password: "كلمة المرور الجديدة",
        users_status_active: "حساب نشط",
        users_status_inactive: "حساب معطل / محظور",

        // Audit Logs
        audit_title: "سجل التدقيق والأمان",
        audit_sub: "سجل مؤمن وغير قابل للتعديل يتتبع جميع العمليات وحركات العتاد.",
        audit_event: "نوع الحدث / العملية",
        audit_module: "الوحدة المعنية",
        audit_user: "المستخدم المنفذ",
        audit_ip: "عنوان IP",
        audit_date: "التاريخ والوقت",
        audit_details: "تفاصيل العملية",

        // Print Discharge (A4 Sheet)
        print_title: "استمارة تسليم وتكليف بالعتاد المعلوماتي",
        print_doc_ready: "وثيقة رسمية جاهزة للطباعة بصيغة A4",
        print_button: "طباعة الاستمارة",
        print_heading: "استمارة تسليم وتكليف بالعتاد المعلوماتي",
        print_discharge_title: "استمارة تسليم وتعيين عتاد معلوماتي",
        print_ref: "مرجع التعيين",
        print_date: "تاريخ التحرير",
        print_section_beneficiary: "معلومات المستفيد",
        print_section_materiel: "مواصفات العتاد المسلّم",
        print_section_commitments: "التزامات المستفيد وشروط الاستخدام",
        print_term_1: "يلتزم المستفيد باستعمال العتاد حصرياً في إطار المهام المهنية ووفقاً لميثاق الاستخدام المعلوماتي للمؤسسة.",
        print_term_2: "يلتزم بالحفاظ على سلامة العتاد وأمانه المادي والرقمي وعدم إجراء أي تعديل تقني غير مرخص.",
        print_term_3: "يجب التبليغ الفوري لمديرية نظم المعلومات عن أي عطل، فقدان، تلف أو حادث يلحق بالعتاد.",
        print_term_4: "يظل العتاد ملكاً حصرياً للمؤسسة، ويتعين إرجاعه فور انتهاء المهام أو بناءً على طلب إدارة النظم.",
        print_section_signatures: "التوقيعات والمصادقة",
        print_sig_beneficiary: "المستفيد",
        print_sig_beneficiary_sub: "التوقيع مسبوق بعبارة «قرأت ووافقت»",
        print_sig_supervisor: "المسؤول المباشر",
        print_sig_supervisor_sub: "الاسم والتأشيرة والخاتم",
        print_sig_dsitd: "مديرية نظم المعلومات",
        print_sig_dsitd_sub: "تأشيرة مسؤول العتاد والمصادقة",
        materiels_name: "التسمية",
        materiels_category: "الفئة",
        materiels_brand: "العلامة التجارية",
        materiels_model: "النموذج",
        materiels_serial: "الرقم التسلسلي",
        materiels_inventory: "رقم الجرد",

        // Alerts & Validation
        alert_success_operation: "تمت العملية بنجاح.",
        alert_error_operation: "حدث خطأ أثناء معالجة الطلب.",
        alert_duplicate_detected: "تم اكتشاف تكرار لبيانات فريدة.",

        // Welcome Page Translation Keys
        system_title: "إدارة العتاد المعلوماتي",
        system_subtitle: "النظام التنفيذي",
        hero_badge: "نظام تشغيلي ومطابق للمواصفات v2.0",
        hero_title_1: "الإدارة التنفيذية لـ",
        hero_title_2: "العتاد المعلوماتي",
        hero_desc: "تتبع كامل للمعدات المعلوماتية، إدارة التعيينات حسب الموظفين، تنبيهات التجديد وسجل تدقيق آمن.",
        go_to_dashboard: "الانتقال إلى لوحة التحكم ←",
        login_access: "تسجيل الدخول الآمن ←",
        workspace_access: "مساحة العمل ←",
        live_preview_title: "معاينة مباشرة للوحة التحكم",
        live_preview_desc: "بيانات العتاد المباشرة في الوقت الفعلي",
        stat_total_title: "جرد العتاد",
        stat_total_sub: "إجمالي المعدات",
        stat_total_desc: "تتبع بالرقم التسلسلي ورمز الجرد",
        stat_stock_title: "المخزون والأمان",
        stat_stock_sub: "المتوفـر بالمخزن",
        stat_stock_desc: "تدقيق مستمر ورقابة على الصلاحيات",
        login_btn: "تسجيل الدخول",
        register_btn: "إنشاء حساب",
        create_account: "إنشاء حساب جديد",
        no_account: "ليس لديك حساب بعد؟",
        already_account: "لديك حساب بالفعل؟",
        remember_me: "تذكرني",
        forgot_password: "نسيت كلمة المرور؟",
        login_title: "تسجيل الدخول إلى حسابك",
        login_subtitle: "الولوج إلى منصة إدارة حظيرة العتاد المعلوماتي",
        register_title: "إنشاء حساب مستخدم جديد",
        register_subtitle: "الانضمام إلى منصة إدارة حظيرة العتاد المعلوماتي",
        name_label: "الاسم الكامل",
        email_label: "البريد الإلكتروني",
        password_label: "كلمة المرور",
        confirm_password_label: "تأكيد كلمة المرور",
        // Achats & Fournisseurs & Stocks
        achats_stocks: "المشتريات والمخزون",
        fournisseurs: "الموردون",
        fournisseurs_title: "دليل الموردين",
        fournisseurs_subtitle: "إدارة الشركات والمزودين وشركاء التوريد",
        fournisseurs_add: "مورد جديد",
        fournisseurs_edit: "تعديل بيانات المورد",
        fournisseur_name: "اسم المورد",
        fournisseur_address: "العنوان",
        fournisseur_phone: "الهاتف",
        fournisseur_contact: "الشخص المسؤول",
        fournisseur_achats_count: "الصفقات والمشتريات المرتبطة",

        achats: "المشتريات والصفقات",
        achats_title: "إدارة المشتريات والصفقات",
        achats_subtitle: "متابعة أوامر الشراء، الصفقات وسندات الطلب",
        achats_add: "طلب شراء / صفقة جديدة",
        achats_edit: "تعديل بيانات الشراء",
        achat_numero: "رقم الصفقة / الشراء",
        achat_objet: "موضوع الطلبية",
        achat_type: "نوع الشراء",
        achat_date: "تاريخ الطلب",
        achat_statut: "الحالة",
        achat_total_ht: "المبلغ الإجمالي دون احتساب الرسوم (HT)",
        achat_total_ttc: "المبلغ الإجمالي مع الرسوم (TTC)",
        achat_lignes_count: "عدد بنود الطلبية",
        achat_qte_totale: "الكمية المطلوبة الإجمالية",
        achat_qte_recue: "الكمية المستلمة بالمخزن",
        achat_details: "تفاصيل الصفقة وبنود العتاد",
        filter_achat: "تصفية حسب الصفقة / الشراء",
        all_achats: "جميع الصفقات / المشتريات",

        bordereau_title: "جدول الأسعار وبنود العتاد",
        bordereau_add_line: "إضافة بند إلى الصفقة",
        bordereau_designation: "نوع العتاد والمواصفات",
        bordereau_specs: "المواصفات التقنية",
        bordereau_qte: "الكمية المطلوبة",
        bordereau_garantie: "الضمان (بالأشهر)",
        bordereau_pu_ht: "سعر الوحدة دون رسوم (درهم)",
        bordereau_total_ht: "المجموع دون رسوم",
        bordereau_delivered: "تم استلامه",
        bordereau_remaining: "المتبقي للتوريد",

        factures: "الفواتير",
        factures_title: "متابعة فواتير الموردين",
        factures_subtitle: "التسجيل المحاسبي والتحقق من المبالغ والأداء",
        factures_add: "تسجيل فاتورة جديدة",
        facture_numero: "رقم الفاتورة",
        facture_date: "تاريخ الفاتورة",
        facture_montant_ht: "المبلغ دون رسوم",
        facture_tva: "نسبة الضريبة (%)",
        facture_montant_ttc: "المبلغ الإجمالي مع الرسوم",

        livraisons: "التوريدات والمخزون",
        livraisons_title: "سندات التسليم واستلام المخزون",
        livraisons_subtitle: "إدخال المعدات للمخزن وتسجيل أرقام الجرد",
        livraisons_add: "تسجيل سند استلام (BL) جديد",
        livraison_ref: "مرجع سند التسليم (BL)",
        livraison_date: "تاريخ الاستلام",
        livraison_qte: "الكمية المستلمة",
        livraison_auto_generate: "توليد بطاقات جرد العتاد تلقائياً في النظام",
        livraison_prefix: "رمز بادئة رقم الجرد",

        marques_modeles: "العلامات والنماذج",
        marques_title: "دليل العلامات التجارية والنماذج",
        marques_subtitle: "سجل الشركات المصنعة ونماذج الأجهزة",
        marques_add: "علامة تجارية جديدة",
        marques_edit: "تعديل العلامة",
        modeles_add: "نموذج جديد",
        modeles_edit: "تعديل النموذج",
        marque_name: "اسم العلامة التجارية",
        modele_name: "اسم النموذج",
        modeles_count: "عدد النماذج",

        bulk_import: "استيراد مجمّع",
        bulk_import_btn: "📥 استيراد ملف Excel / CSV",
        bulk_import_title: "استيراد العتاد بشكل مجمّع",
        bulk_import_subtitle: "قم برفع ملف Excel أو CSV لإنشاء عدة معدات دفعة واحدة.",
        bulk_import_download_template: "تحميل نموذج ملف Excel / CSV",
        bulk_import_file_label: "ملف Excel / CSV (.csv, .xlsx, .xls)",
        bulk_import_submit: "بدء الاستيراد",
        bulk_import_results: "نتائج الاستيراد",
        materiel_achat: "عقد الشراء / الصفقة الأصلية",
        materiel_achat_placeholder: "-- اختر صفقة شراء (اختياري) --",

        feature_structure_title: "الهيكل التنظيمي",
        feature_structure_desc: "تقسيم هرمي شامل حسب المديريات، الأقسام، المصالح والخدمات مع ربط الموظفين بها مباشرة.",
        feature_parc_title: "العتاد والتعيينات",
        feature_parc_desc: "تعيين أجهزة الكمبيوتر، الشاشات والملحقات مع إدارة الاسترجاع، الإغلاق واستمارات A4.",
        feature_security_title: "الأمان وسجل التدقيق",
        feature_security_desc: "سجل غير قابل للتزوير يتتبع جميع عمليات الإنشاء، التعديل والإغلاق مع التوقيت الزمني الدقيق.",
        footer_internal: "— نظام الإدارة الداخلي",
        footer_rights: "جميع الحقوق محفوظة."
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [locale, setLocale] = useState(() => {
        return localStorage.getItem('app_locale') || 'fr';
    });

    const [darkMode, setDarkMode] = useState(() => {
        return localStorage.getItem('app_theme') === 'dark';
    });

    useEffect(() => {
        localStorage.setItem('app_locale', locale);
        document.documentElement.setAttribute('lang', locale);
        document.documentElement.setAttribute('dir', 'ltr');
    }, [locale]);

    useEffect(() => {
        localStorage.setItem('app_theme', darkMode ? 'dark' : 'light');
        if (darkMode) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    }, [darkMode]);

    const t = (key, params = {}) => {
        let text = translations[locale]?.[key] || translations['fr']?.[key] || key;
        if (params && typeof params === 'object') {
            Object.entries(params).forEach(([k, v]) => {
                text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
            });
        }
        return text;
    };

    const toggleDarkMode = () => setDarkMode((prev) => !prev);

    return (
        <LanguageContext.Provider value={{ locale, setLocale, darkMode, toggleDarkMode, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        return {
            locale: 'fr',
            setLocale: () => {},
            darkMode: false,
            toggleDarkMode: () => {},
            t: (key, params = {}) => {
                let text = translations['fr']?.[key] || key;
                if (params && typeof params === 'object') {
                    Object.entries(params).forEach(([k, v]) => {
                        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
                    });
                }
                return text;
            },
        };
    }
    return context;
}
